from __future__ import annotations

import json
import os
import re
import socket
import urllib.error
import urllib.parse
import urllib.request
from typing import Any

# 数值一致性校验用：匹配文本里的数字（含小数、千分位逗号）
_NUMBER_PATTERN = re.compile(r"\d[\d,]*(?:\.\d+)?")

# 附在每个提示词末尾的数值纪律。
#
# 实测（deepseek-chat，8 次真实调用）：只写"不得新增数字"时仍有 88% 的返回被
# 数值校验拦下，编造的清一色是**阈值**——"寻找成本评分不低于 60 的方案"这类。
# 根因是 suggested_revision 这种字段的语义在诱导模型给目标值。因此这里不止说
# "不许"，而是明确给出替代写法：只描述方向，不给数字。
_NUMBER_DISCIPLINE = (
    "\n严格约束（违反则整段作废）：\n"
    "1. 只能引用上面已给出的数字，一个都不能新增、修改或推算。\n"
    "2. 禁止提出任何目标值、阈值、区间或百分比，包括『不低于X』『控制在X以内』\n"
    "   『提升至X』『降低到X』这类表述。需要表达改进方向时只用定性描述，\n"
    "   例如『选择成本分值更高的方案』，而不是『选择成本分值不低于60的方案』。\n"
    "3. 不要自行给论点编号，编号由程序处理。"
)
# 浮点比较容差：仅用于消化 28 与 28.0 这类写法差异，不做量纲换算
_NUMBER_TOLERANCE = 1e-6

OLLAMA_ENDPOINT = "http://localhost:11434/api/generate"
OLLAMA_MODEL = "qwen2.5"
# DeepSeek 是 OpenAI 兼容接口，因此走 chat/completions 而非 Ollama 的 /api/generate
DEEPSEEK_ENDPOINT = "https://api.deepseek.com/chat/completions"
DEEPSEEK_MODEL = "deepseek-chat"


class TextGenerator:
    """把代码算好的结论翻译成自然语言。

    两条后端可选，行为完全一致地受同一套安全约束：

      - ``ollama``   本地模型（默认 qwen2.5），离线可用
      - ``deepseek`` 远程 API，需要 DEEPSEEK_API_KEY

    不变的安全属性（接入新后端时**不得**削弱）：

      1. 模型返回必须是 JSON 且通过 ``_matches_schema`` 结构校验才被采用；
      2. 任何异常/超时/结构不符一律落确定性模板，不抛给调用方；
      3. 每段输出自带 ``llm_used`` 与 ``model_name``，界面据此区分
         "算法结论"与"AI 生成解释"。

    后端选择顺序：显式 provider 参数 > CHAINGUARD_LLM_PROVIDER 环境变量 >
    有 DEEPSEEK_API_KEY 则 deepseek > 否则 ollama。
    显式传 endpoint 时固定按 ollama 处理（既有测试用不可达地址验证模板兜底，
    不能因为环境里恰好有 key 就改走远程）。
    """

    def __init__(
        self,
        endpoint: str | None = None,
        model: str | None = None,
        timeout: int = 15,
        provider: str | None = None,
        api_key: str | None = None,
    ) -> None:
        self.provider = self._resolve_provider(provider, endpoint)
        self.timeout = timeout
        if self.provider == "deepseek":
            self.endpoint = endpoint or os.getenv("DEEPSEEK_API_URL") or DEEPSEEK_ENDPOINT
            self.model = model or os.getenv("DEEPSEEK_MODEL") or DEEPSEEK_MODEL
            self.api_key = api_key or os.getenv("DEEPSEEK_API_KEY") or ""
        else:
            self.endpoint = endpoint or OLLAMA_ENDPOINT
            self.model = model or OLLAMA_MODEL
            self.api_key = ""

    @staticmethod
    def _resolve_provider(provider: str | None, endpoint: str | None) -> str:
        if provider:
            return provider.strip().lower()
        configured = (os.getenv("CHAINGUARD_LLM_PROVIDER") or "").strip().lower()
        if configured:
            return configured
        # 显式给了 endpoint 却没指定 provider：按本地 Ollama 处理（见类注释）
        if endpoint:
            return "ollama"
        return "deepseek" if os.getenv("DEEPSEEK_API_KEY") else "ollama"

    def generate_rebuttal_content(
        self,
        *,
        branch: str,
        debater: str,
        target: str,
        proposal_data: dict[str, Any],
        context_data: dict[str, Any],
    ) -> dict[str, Any]:
        """Return rebuttal text generated by Ollama or deterministic templates."""
        template = self._rebuttal_template(
            branch=branch,
            proposal_data=proposal_data,
            context_data=context_data,
        )
        prompt = self._build_rebuttal_prompt(
            branch=branch,
            debater=debater,
            target=target,
            proposal_data=proposal_data,
            context_data=context_data,
        )
        return self._generate_or_template(
            prompt,
            template,
            {
                "rebuttal_points": list,
                "suggested_revision": str,
                "accepted_tradeoff": str,
            },
        )

    def generate_arbitration_content(
        self,
        *,
        action_phrase: str,
        material_name: str,
        event_title: str,
        critical_orders_count: int,
        top_proposals: list[dict[str, Any]],
        final_score: float,
    ) -> dict[str, Any]:
        """Return arbitration narrative generated by Ollama or deterministic templates."""
        template = self._arbitration_template(
            action_phrase=action_phrase,
            material_name=material_name,
            event_title=event_title,
            critical_orders_count=critical_orders_count,
            top_proposals=top_proposals,
            final_score=final_score,
        )
        prompt = self._build_arbitration_prompt(
            action_phrase=action_phrase,
            material_name=material_name,
            event_title=event_title,
            critical_orders_count=critical_orders_count,
            top_proposals=top_proposals,
            final_score=final_score,
        )
        return self._generate_or_template(
            prompt,
            template,
            {
                "final_strategy": str,
                "execution_plan": list,
                "expected_effect": dict,
                "rejected_opinions": list,
                "manual_confirmation_points": list,
            },
        )

    def generate_experience_narrative(
        self,
        *,
        outcome_status: str,
        scenario_desc: str,
        event_title: str,
        strategy_desc: str,
    ) -> dict[str, Any]:
        """Return experience-card narrative generated by Ollama or templates."""
        template = self._experience_template(
            outcome_status=outcome_status,
            scenario_desc=scenario_desc,
            event_title=event_title,
            strategy_desc=strategy_desc,
        )
        prompt = self._build_experience_prompt(
            outcome_status=outcome_status,
            scenario_desc=scenario_desc,
            event_title=event_title,
            strategy_desc=strategy_desc,
        )
        return self._generate_or_template(
            prompt,
            template,
            {
                "failed_reason": str,
                "improvement_strategy": str,
                "recommended_pattern": str,
            },
        )

    def _generate_or_template(
        self,
        prompt: str,
        template: dict[str, Any],
        schema: dict[str, type],
    ) -> dict[str, Any]:
        rejected_reason = ""
        try:
            parsed = self._call_model_json(prompt)
            if not self._matches_schema(parsed, schema):
                rejected_reason = "schema_mismatch"
            elif not self._numbers_consistent(parsed, prompt):
                # 模型写出了输入里没有的数字：整段作废，绝不放行
                rejected_reason = "number_mismatch"
            else:
                result = dict(parsed)
                result["llm_used"] = True
                result["model_name"] = self.model
                return result
        except Exception:
            # 网络异常、超时、非 JSON——一律静默落模板。
            # 这里刻意不外抛：表达层失败绝不能让整条决策链失败。
            rejected_reason = "call_failed"

        result = dict(template)
        result["llm_used"] = False
        result["model_name"] = "template"
        if rejected_reason:
            # 落模板的原因要可观测，否则"为什么没用上大模型"只能靠猜
            result["fallback_reason"] = rejected_reason
        return result

    def _call_model_json(self, prompt: str) -> dict[str, Any]:
        if self.provider == "deepseek":
            return self._call_deepseek_json(prompt)
        return self._call_ollama_json(prompt)

    def _call_deepseek_json(self, prompt: str) -> dict[str, Any]:
        if not self.api_key:
            raise ValueError("DEEPSEEK_API_KEY 未配置")
        body = json.dumps(
            {
                "model": self.model,
                "messages": [
                    # 数值由代码算好后写在 prompt 里，模型只负责组织语言。
                    # 这条边界同时写进 system 与各 _build_*_prompt，双重约束。
                    {
                        "role": "system",
                        "content": (
                            "你是供应链决策系统的表达层。只能把给定结论改写成通顺中文，"
                            "必须原样使用输入中的数值与实体名称，禁止新增、修改或推算任何数字。"
                            "只输出一个 JSON 对象，不要输出其它内容。"
                        ),
                    },
                    {"role": "user", "content": prompt},
                ],
                "response_format": {"type": "json_object"},
                # 低温度：表达层要的是稳定复述，不是创造性
                "temperature": 0.2,
                "stream": False,
            },
            ensure_ascii=False,
        ).encode("utf-8")
        request = urllib.request.Request(
            self.endpoint,
            data=body,
            headers={
                "Content-Type": "application/json",
                "Authorization": f"Bearer {self.api_key}",
            },
            method="POST",
        )
        with urllib.request.urlopen(request, timeout=self.timeout) as response:
            payload = json.loads(response.read().decode("utf-8"))
        text = str(payload["choices"][0]["message"]["content"])
        return json.loads(self._extract_json_text(text))

    def _call_ollama_json(self, prompt: str) -> dict[str, Any]:
        self._ensure_local_endpoint_available()
        body = json.dumps(
            {
                "model": self.model,
                "prompt": prompt,
                "stream": False,
            },
            ensure_ascii=False,
        ).encode("utf-8")
        request = urllib.request.Request(
            self.endpoint,
            data=body,
            headers={"Content-Type": "application/json"},
            method="POST",
        )
        with urllib.request.urlopen(request, timeout=self.timeout) as response:
            if getattr(response, "status", 200) != 200:
                raise urllib.error.HTTPError(
                    self.endpoint,
                    getattr(response, "status", 500),
                    "Ollama request failed",
                    getattr(response, "headers", None),
                    None,
                )
            payload = json.loads(response.read().decode("utf-8"))
        response_text = str(payload.get("response", ""))
        return json.loads(self._extract_json_text(response_text))

    def _ensure_local_endpoint_available(self) -> None:
        parsed = urllib.parse.urlparse(self.endpoint)
        if parsed.hostname not in {"localhost", "127.0.0.1", "::1"}:
            return
        port = parsed.port or (443 if parsed.scheme == "https" else 80)
        try:
            with socket.create_connection((parsed.hostname, port), timeout=0.2):
                return
        except OSError as error:
            raise urllib.error.URLError(error) from error

    @staticmethod
    def _extract_json_text(text: str) -> str:
        stripped = text.strip()
        if stripped.startswith("```"):
            stripped = stripped.strip("`").strip()
            if stripped.lower().startswith("json"):
                stripped = stripped[4:].strip()
        start = stripped.find("{")
        end = stripped.rfind("}")
        if start == -1 or end == -1 or end < start:
            raise ValueError("Ollama response does not contain JSON object")
        return stripped[start : end + 1]

    @staticmethod
    def _matches_schema(payload: dict[str, Any], schema: dict[str, type]) -> bool:
        if not isinstance(payload, dict):
            return False
        return all(isinstance(payload.get(key), value_type) for key, value_type in schema.items())

    # ----------------------------------------------------------------- 数值一致性
    #
    # 结构校验只管字段类型，管不了模型有没有把数字写错。而本系统对外的核心承诺是
    # "所有数值由代码计算，LLM 只负责翻译成人话，绝不改数"——那就必须由代码强制，
    # 不能只写在提示词里请求模型配合。
    #
    # 规则：生成文本里出现的每一个数字，都必须在权威输入（提示词，其中的数值全部
    # 由代码算出）中出现过。出现输入里没有的数字 = 模型自行编造或推算，整段作废、
    # 落模板。
    #
    # 刻意选择严格而非宽松：误判的代价是这一段文案退回模板（措辞变死板，
    # 数值仍然正确、llm_used 如实标记为 False），漏判的代价是答辩现场
    # AI 解释里的数字与算法结论对不上。两者不对等，因此宁可多退。

    @staticmethod
    def _collect_numbers(value: Any, sink: set[float]) -> None:
        """递归收集任意结构里出现的数字。"""
        if isinstance(value, bool):
            return  # bool 是 int 的子类，但它不是业务数值
        if isinstance(value, (int, float)):
            sink.add(round(float(value), 6))
            return
        if isinstance(value, str):
            for token in _NUMBER_PATTERN.findall(value):
                try:
                    sink.add(round(float(token.replace(",", "")), 6))
                except ValueError:
                    continue
            return
        if isinstance(value, dict):
            for key, item in value.items():
                TextGenerator._collect_numbers(key, sink)
                TextGenerator._collect_numbers(item, sink)
            return
        if isinstance(value, (list, tuple, set)):
            for item in value:
                TextGenerator._collect_numbers(item, sink)

    @classmethod
    def _numbers_consistent(cls, generated: dict[str, Any], authoritative: str) -> bool:
        """生成文本中的数字必须都来自权威输入。"""
        allowed: set[float] = set()
        cls._collect_numbers(authoritative, allowed)

        produced: set[float] = set()
        cls._collect_numbers(generated, produced)

        for number in produced:
            if not any(abs(number - candidate) <= _NUMBER_TOLERANCE for candidate in allowed):
                return False
        return True

    @staticmethod
    def _rebuttal_template(
        *,
        branch: str,
        proposal_data: dict[str, Any],
        context_data: dict[str, Any],
    ) -> dict[str, Any]:
        proposal_title = str(proposal_data.get("proposal_title") or "当前方案")
        scores = proposal_data.get("scores") or {}
        event_title = str(context_data.get("event_title") or "当前事件")
        material_name = str(context_data.get("material_name") or "关键物料")
        n = int(context_data.get("critical_orders_count") or 0)

        if branch == "high_cost":
            cost_score = float(scores.get("cost") or 50)
            return {
                "rebuttal_points": [
                    f"{proposal_title}成本分值({cost_score:.0f}/100)偏低，会压缩利润空间。",
                    f"在{event_title}背景下，高成本运输应聚焦履约损失最大的订单。",
                    f"建议仅对{n}个A类关键订单启用高成本运输，其余订单组合降本。",
                ],
                "suggested_revision": (
                    f"将{proposal_title}修订为分级保障：优先保障{n}个A类订单时效，"
                    "其余订单采用客户沟通与低成本运输组合。"
                ),
                "accepted_tradeoff": "接受非关键订单时效让步，换取关键客户履约和整体利润可控。",
            }

        if branch == "missing_backup":
            return {
                "rebuttal_points": [
                    f"{event_title}导致主供应商受影响，继续依赖单一来源存在断货风险。",
                    f"{proposal_title}缺少明确备用供应商安排，难以保障{n}个A类订单。",
                    f"应提前锁定备用供应商，避免{material_name}库存过早耗尽。",
                ],
                "suggested_revision": "补充备用供应商紧急采购计划，并保留第二梯队供应商作为小批量兜底。",
                "accepted_tradeoff": "接受一定采购溢价，换取供应连续性和关键订单覆盖率保障。",
            }

        if branch == "conservative":
            timeliness = float(scores.get("timeliness") or 50)
            return {
                "rebuttal_points": [
                    f"{proposal_title}时效分值({timeliness:.0f}/100)偏低，可能错过交付窗口。",
                    f"若不对{n}个A类关键客户启用高时效运输，存在违约风险。",
                    "应为关键订单保留最快可用的替代路线或运输方式。",
                ],
                "suggested_revision": (
                    f"对{n}个A类关键订单启用高时效运输，"
                    "非关键订单采用低成本替代方案组合。"
                ),
                "accepted_tradeoff": "接受关键订单运输成本上升，以降低违约风险和客户服务风险。",
            }

        return {
            "rebuttal_points": [
                "当前最高分方案存在未充分解释的执行约束，需要进一步说明。",
                "成本、时效、风险降低和客户服务之间的取舍尚未明确量化。",
            ],
            "suggested_revision": "将高分方案拆分为关键订单优先和非关键订单分级处理两个执行路径。",
            "accepted_tradeoff": "接受局部成本或时效让步，获得更稳健的综合方案。",
        }

    @staticmethod
    def _arbitration_template(
        *,
        action_phrase: str,
        material_name: str,
        event_title: str,
        critical_orders_count: int,
        top_proposals: list[dict[str, Any]],
        final_score: float,
    ) -> dict[str, Any]:
        top_title = (
            str(top_proposals[0].get("proposal_title") or action_phrase)
            if top_proposals
            else action_phrase
        )
        parts = [part.strip() for part in action_phrase.split("+") if part.strip()]
        primary_action = parts[0] if parts else action_phrase
        return {
            "final_strategy": (
                f"围绕{material_name}的断供风险，采用{action_phrase}综合策略；"
                f"触发事件为{event_title}。以评分最高方案({top_title})为基准，"
                f"最终评分为{final_score:.1f}，兼顾交期、成本和客户优先级。"
            ),
            "execution_plan": [
                f"立即联系备用供应商确认{material_name}可供量与交期。",
                f"对{critical_orders_count}个A类关键客户订单启用优先保障({primary_action})。",
                "与非关键客户沟通延期，制定分批交付和替代运输计划。",
                f"若{event_title}影响超过72小时，启动第二梯队应急供应预案。",
            ],
            "expected_effect": {
                "supply_continuity": f"通过{action_phrase}，{material_name}供应连续性预计显著改善。",
                "delivery_risk": (
                    f"{critical_orders_count}个A类客户交付风险因资源优先配置而降低。"
                ),
                "cost_risk": "总体成本风险可控，分级保障避免单一高成本方案覆盖全部订单。",
                "customer_impact": (
                    f"{critical_orders_count}个A类客户优先保障；"
                    "非关键客户通过提前沟通降低投诉风险。"
                ),
            },
            "rejected_opinions": [
                "拒绝单一运输方案覆盖全部受影响订单：低毛利订单利润转负风险较高。",
            ],
            "manual_confirmation_points": [
                f"是否接受对A类订单的优先保障成本安排({primary_action})。",
                f"是否启用备用供应商补充{material_name}库存缺口。",
                "非关键订单延期计划是否已与客户确认，避免投诉风险。",
            ],
        }

    @staticmethod
    def _experience_template(
        *,
        outcome_status: str,
        scenario_desc: str,
        event_title: str,
        strategy_desc: str,
    ) -> dict[str, Any]:
        failed_reason = (
            f"在{event_title}场景下，{strategy_desc}执行效果不佳，"
            "主要原因是资源分配未充分考虑订单优先级分布。"
        ) if outcome_status == "failed" else ""
        partial_note = (
            f"在{event_title}场景下，{strategy_desc}部分达成目标，"
            "部分环节执行偏差导致结果不完整。"
        ) if outcome_status == "partial" else ""
        return {
            "failed_reason": failed_reason or partial_note,
            "improvement_strategy": (
                f"在{event_title}类场景中，建议优先评估{strategy_desc}对A类订单覆盖率的影响，"
                "再决定资源分配优先级。"
            ),
            "recommended_pattern": (
                f"基于{scenario_desc}的历史经验，推荐{strategy_desc}模式，"
                "并结合客户订单优先级进行分级保障。"
            ),
        }

    @staticmethod
    def _build_rebuttal_prompt(
        *,
        branch: str,
        debater: str,
        target: str,
        proposal_data: dict[str, Any],
        context_data: dict[str, Any],
    ) -> str:
        proposal_title = str(proposal_data.get("proposal_title") or "当前方案")
        scores = proposal_data.get("scores") or {}
        return (
            "你是供应链应急决策系统的辩论分析引擎。请只根据结构化数据生成中文 JSON。\n"
            f"辩论方：{debater}\n"
            f"目标方：{target}\n"
            f"原因类型：{branch}\n"
            f"目标方案：{proposal_title}\n"
            f"评分：{json.dumps(scores, ensure_ascii=False)}\n"
            f"事件：{context_data.get('event_title', '当前事件')}\n"
            f"物料：{context_data.get('material_name', '关键物料')}\n"
            f"A类关键订单数：{context_data.get('critical_orders_count', 0)}\n"
            # 必须写明类型：只说键名时模型会把 rebuttal_points 返回成一个整段字符串，
            # 结构校验判失败 → 白白落模板。实测 deepseek-chat 与 qwen2.5 都会这样。
            "返回 JSON，字段与类型必须严格如下：\n"
            "  rebuttal_points: 字符串数组（3 条，每条一句独立论点）\n"
            "  suggested_revision: 字符串\n"
            "  accepted_tradeoff: 字符串\n"
            + _NUMBER_DISCIPLINE
        )

    @staticmethod
    def _build_arbitration_prompt(
        *,
        action_phrase: str,
        material_name: str,
        event_title: str,
        critical_orders_count: int,
        top_proposals: list[dict[str, Any]],
        final_score: float,
    ) -> str:
        return (
            "你是供应链应急决策系统的仲裁文本生成引擎。请只根据结构化数据生成中文 JSON。\n"
            f"行动组合：{action_phrase}\n"
            f"物料：{material_name}\n"
            f"事件：{event_title}\n"
            f"A类关键订单数：{critical_orders_count}\n"
            f"最高分方案：{json.dumps(top_proposals, ensure_ascii=False)}\n"
            f"最终评分：{final_score:.1f}\n"
            "返回 JSON，字段与类型必须严格如下：\n"
            "  final_strategy: 字符串\n"
            "  execution_plan: 字符串数组（每条一个执行步骤）\n"
            "  expected_effect: 对象（键为效果维度，值为字符串描述）\n"
            "  rejected_opinions: 字符串数组\n"
            "  manual_confirmation_points: 字符串数组\n"
            + _NUMBER_DISCIPLINE
        )

    @staticmethod
    def _build_experience_prompt(
        *,
        outcome_status: str,
        scenario_desc: str,
        event_title: str,
        strategy_desc: str,
    ) -> str:
        return (
            "你是供应链应急经验卡片叙述生成引擎。请只根据结构化数据生成中文 JSON。\n"
            f"结果状态：{outcome_status}\n"
            f"场景描述：{scenario_desc}\n"
            f"事件：{event_title}\n"
            f"策略：{strategy_desc}\n"
            "返回 JSON，字段与类型必须严格如下：\n"
            "  failed_reason: 字符串\n"
            "  improvement_strategy: 字符串\n"
            "  recommended_pattern: 字符串\n"
            + _NUMBER_DISCIPLINE
        )

